apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-con-bug
  namespace: lab-troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-con-bug
  template:
    metadata:
      labels:
        app: app-con-bug
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Crasheando intencionadamente'; exit 1"]
