apiVersion: v1
kind: Pod
metadata:
  name: app-dep
  namespace: lab-troubleshooting
  labels:
    app: app-dep
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo 'Arrancando...'; sleep 3600"]
      env:
        - name: MI_CONFIG
          valueFrom:
            configMapKeyRef:
              name: config-inexistente
              key: data.key
