apiVersion: v1
kind: Pod
metadata:
  name: consumesec
spec:
  containers:
    - name: shell
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: apikey
              key: apikey
      volumeMounts:
        - name: apikey-volume
          mountPath: /etc/apikey
          readOnly: true
  volumes:
    - name: apikey-volume
      secret:
        secretName: apikey
