apiVersion: batch/v1
kind: Job
metadata:
  name: report-once
  namespace: cka-scheduling-lab
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: report-once
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cka.formacion.io/pool
                    operator: In
                    values:
                      - batch
      containers:
        - name: report
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Generating one-shot report..."
              date
              sleep 10
              echo "Report completed."