apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-web
  labels:
    app: tienda-web
    modulo: "5"
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tienda-web
  template:
    metadata:
      labels:
        app: tienda-web
        version: v1
    spec:
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
