apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-web
  labels:
    app: tienda-web
    modulo: "5"
  annotations:
    kubernetes.io/change-cause: "Cambio intencionadamente erróneo a una imagen inexistente"
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tienda-web
  template:
    metadata:
      labels:
        app: tienda-web
        version: v2-error
    spec:
      containers:
        - name: web
          image: nginx:version-inexistente-modulo5
          ports:
            - containerPort: 80
