apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: auditor-nodo-control-plane
  labels:
    app: auditor-nodo-control-plane
    modulo: "5"
spec:
  selector:
    matchLabels:
      app: auditor-nodo-control-plane
  template:
    metadata:
      labels:
        app: auditor-nodo-control-plane
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: auditor
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              while true; do
                echo "DaemonSet con toleration ejecutándose en: $(hostname)"
                date
                sleep 20
              done
