apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemonset-running
spec:
  selector:
    matchLabels:
      app: hello-daemonset-running
  template:
    metadata:
      labels:
        app: hello-daemonset-running
    spec:
      containers:
      - name: hello-container
        image: busybox:1.36
        command: ["/bin/sh", "-c", "while true; do echo \"Hello from $(hostname) at $(date)\"; sleep 30; done"]
