apiVersion: v1
kind: Service
metadata:
  name: catalog-web
  namespace: svc-troubleshooting
  labels:
    app: catalog-web
    exercise: troubleshooting
spec:
  type: ClusterIP
  selector:
    # ERROR INTENCIONADO:
    # Los Pods tienen app=catalog-web, pero el Service busca app=catalog.
    app: catalog
    component: frontend
  ports:
    - name: http
      port: 80
      # ERROR INTENCIONADO:
      # nginx escucha en el puerto 80, no en el 8080.
      targetPort: 8080
      protocol: TCP
