apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modulo10-web.fullname" . }}
  labels:
    {{- include "modulo10-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "modulo10-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "modulo10-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: html
        configMap:
          name: {{ include "modulo10-web.fullname" . }}-html
