apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-config
  namespace: m7-troubleshooting
data:
  application.properties: |
    app.name=Sistema de informes
    app.environment=lab
    app.logLevel=INFO
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
