apiVersion: v1
kind: Secret
metadata:
  name: reporting-db-secret
  namespace: m7-troubleshooting
type: Opaque
stringData:
  db-user: report_user
  # Error intencionado: el Deployment buscará la clave db-password,
  # pero aquí se ha creado como db_pass.
  db_pass: supersecreto123
