apiVersion: v1
kind: Service
metadata:
  name: reporting-web
  namespace: m7-troubleshooting
spec:
  type: ClusterIP
  selector:
    app: reporting-web
  ports:
    - name: http
      port: 80
      targetPort: 80
