apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefuldaemonset-controller
  namespace: sds-lab-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sds-lab-controller
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["lab.formacion.cloud"]
    resources: ["statefuldaemonsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["lab.formacion.cloud"]
    resources: ["statefuldaemonsets/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sds-lab-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sds-lab-controller
subjects:
  - kind: ServiceAccount
    name: statefuldaemonset-controller
    namespace: sds-lab-system
