apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeselector
  labels:
    app: scheduling-demo
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
